Add specter file and deps
latacora/clojure-koans pull request #1
Opened 2021-02-08 23:21 UTC by pfarwick-latacora

Making draft PR for adding specter training to koans. 

Will hopefully be updating every day so not going to merge just yet

2021-02-09 18:57 UTC, lvh commented on src/koans/28_specter.clj
> +                                   :color "green"}]}}})
No Guards Red 1986 911 Turbo?

Unacceptable.

2021-02-09 18:57 UTC, lvh requested changes
Never used Koan engine before, looks sweet! Also, no 911, unacceptable, what the fuck

2021-02-10 18:48 UTC, latacora-lizzie commented
:+1: exciting!

2021-02-23 15:38 UTC, pfarwick-latacora commented
@lvh as if you would ever sell the 911 at our make believe car dealership. 

How dare you actually!

2021-02-23 15:39 UTC, pfarwick-latacora commented
I am sure we can add more to this in the future but I think it gets people familiar enough with specter and eidolon in order to understand / work on edit.clj files in a meaningful enough way.

2021-02-23 15:59 UTC, lvh approved these changes

2021-02-23 15:59 UTC, merged